services:
  postgres:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postbee-app_user
      POSTGRES_PASSWORD: postbee-app_password
      POSTGRES_DB: postbee-app_database
      TZ: "Europe/Zurich"
      PGTZ: "Europe/Zurich"
